spring:
  application:
    name: Rating-service
  data:
    mongodb:
      uri: mongodb+srv://krupalichotaliya9:hOd1GcljbRFdd83U@cluster0.oghims0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: Rating-microService
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  config:
    import: configserver:http://localhost:8085
server:
  port: 8083

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true